# Paso 1: Definir las palabras clave y unificar sinónimos
keywords = {

    "Habilidades": {
        "Abstraction": ["Abstraction", "abstraction"],
        "Algorithm": ["Algorithm", "algorithm"],
        "Algorithmic thinking": ["Algorithmic thinking", "algorithmic thinking"],
        "Coding": ["Coding", "coding"],
        "Collaboration": ["Collaboration", "Cooperation", "cooperation", "collaboration"],
        "Creativity": ["Creativity", "creativity"],
        "Critical thinking": ["Critical thinking", "critical thinking"],
        "Debug": ["Debug", "debug"],
        "Decomposition": ["Decomposition", "decomposition"],
        "Evaluation": ["Evaluation", "evaluation"],
        "Generalization": ["Generalization", "generalization"],
        "Logic": ["Logic", "logic"],
        "Modularity": ["Modularity", "modularity"],
        "Patterns recognition": ["Patterns recognition", "patterns recognition"],
        "Problem solving": ["Problem solving", "problem solving"],
        "Programming": ["Programming", "programming"],
    },
    "Conceptos Computacionales": {
        "Conditionals": ["Conditionals", "conditionals"],
        "Control structures": ["Control structures", "control structures"],
        "Directions": ["Directions", "directions"],
        "Events": ["Events", "events"],
        "Functions": ["Functions", "functions"],
        "Loops": ["Loops", "loops"],
        "Modular structure": ["Modular structure", "modular structure"],
        "Parallelism": ["Paralelism", "paralelism"],
        "Sequences": ["Sequences", "sequences"],
        "Software/Hardware": ["Software/Hardware", "software/hardware"],
        "Variables": ["Variables", "variables"],
    },
    "Actitudes": {
        "Emotional": ["Emotional", "emotional"],
        "Engagement": ["Engagement", "engagement"],
        "Motivation": ["Motivation", "motivation"],
        "Perception": ["Perception", "perception", "perceptions", "Perceptions"],
        "Persistence": ["Persistence", "persistence"],
        "Self-efficacy": ["Self-efficacy", "self-efficacy"],
        "Self-perceived": ["Self-perceived", "self-perceived"],
    },
    "Propiedades Psicométricas": {
        "Classical Test Theory": ["Classical Test Theory", "CTT", "ctt", "classical test theory"],
        "Confirmatory Factor Analysis": ["Confirmatory Factor Analysis", "CFA", "cfa", "confirmatory factor analysis"],
        "Exploratory Factor Analysis": ["Exploratory Factor Analysis", "EFA", "efa", "exploratory factor analysis"],
        "Item Response Theory": ["Item Response Theory", "IRT", "irt", "item response theory"],
        "Reliability": ["Reliability", "reliability"],
        "Structural Equation Model": ["Structural Equation Model", "SEM", "structural equation model", "sem"],
        "Validity": ["Validity", "validity"],
    },
    "Herramientas de Evaluación": {
        "Beginners Computational Thinking test": ["Beginners Computational Thinking test", "BCTt"],
        "Coding Attitudes Survey": ["Coding Attitudes Survey", "ESCAS"],
        "Collaborative Computing Observation Instrument": ["Collaborative Computing Observation Instrument"],
        "Competent Computational Thinking test": ["Competent Computational Thinking test", "cCTt"],
        "Computational thinking skills test": ["Computational thinking skills test", "CTST"],
        "Computational concepts": ["Computational concepts"],
        "Computational Thinking Assessment for Chinese Elementary Students": ["Computational Thinking Assessment for Chinese Elementary Students", "CTA-CES"],
        "Computational Thinking Challenge": ["Computational Thinking Challenge", "CTC"],
        "Computational Thinking Levels Scale": ["Computational Thinking Levels Scale", "CTLS"],
        "Computational Thinking Scale": ["Computational Thinking Scale", "CTS"],
        "Computational Thinking Skill Levels Scale": ["Computational Thinking Skill Levels Scale", "CTS"],
        "Computational Thinking Test": ["Computational Thinking Test", "CTt"],
        "Computational Thinking Test for Elementary School Students": ["Computational Thinking Test for Elementary School Students"],
        "Computational Thinking Test for Lower Primary": ["Computational Thinking Test for Lower Primary", "CTtLP"],
        "Computational thinking-skill tasks on numbers and arithmetic": ["Computational thinking-skill tasks on numbers and arithmetic"],
        "Computerized Adaptive Programming Concepts Test": ["Computerized Adaptive Programming Concepts Test", "CAPCT"],
        "CT Scale": ["CT Scale", "CTS"],
        "Elementary Student Coding Attitudes Survey": ["Elementary Student Coding Attitudes Survey", "ESCAS"],
        "General self-efficacy scale": ["General self-efficacy scale"],
        "ICT competency test": ["ICT competency test"],
        "Instrument of computational identity": ["Instrument of computational identity"],
        "KBIT fluid intelligence subtest": ["KBIT fluid intelligence subtest"],
        "Mastery of computational concepts Test and an Algorithmic Test": ["Mastery of computational concepts Test and an Algorithmic Test"],
        "Multidimensional 21st Century Skills Scale": ["Multidimensional 21st Century Skills Scale"],
        "Self-efficacy scale": ["Self-efficacy scale"],
        "STEM learning attitude scale": ["STEM learning attitude scale"],
        "The computational thinking scale": ["The computational thinking scale"]
    },
    "Diseño de Investigación": {
        "No experimental": ["No experimental", "no experimental"],
        "Experimental": ["Experimental", "experimental"],
        "Longitudinal research": ["Longitudinal research", "longitudinal research"],
        "Mixed methods": ["Mixed methods", "mixed methods"],
        "Post-test": ["Post-test", "post-test"],
        "Pre-test": ["Pre-test", "pre-test"],
        "Quasi-experiments": ["Quasi-experiments", "quasi-experiments"],
    },
    "Nivel de Escolaridad": {
        "Upper Elementary Education": ["Upper Elementary Education", "upper elementary education", "Upper elementary school", "upper elementary school"],
        "Primary School": ["Primary School", "primary school", "Primary education", "primary education", "Elementary school", "elementary school"],
        "Early Childhood Education": ["Early Childhood Education", "early childhood education", "Preschool", "preschool", "Kindergarten", "kindergarten"],
        "Secondary School": ["Secondary School", "secondary school", "Secondary education", "secondary education"],
        "High School": ["High School", "high school", "Higher education", "higher education"],
        "University": ["University", "university", "College", "college"],
    },
    "Medio": {
        "Block programming": ["Block programming", "block programming"],
        "Mobile application": ["Mobile application", "mobile application"],
        "Pair programming": ["Pair programming", "pair programming"],
        "Plugged activities": ["Plugged activities", "plugged activities"],
        "Programming": ["Programming:", "programming:"],
        "Robotics": ["Robotics", "robotics"],
        "Spreadsheet": ["Spreadsheet", "spreadsheet"],
        "STEM": ["STEAM", "steam"],
        "Unplugged activities": ["Unplugged activities", "unplugged activities"],
    },
    "Estrategias": {
        "Construct-by-self mind mapping": ["Construct-by-self mind mapping"],
        "Construct-on-scaffold mind mapping": ["Construct-on-scaffold mind mapping"],
        "Design-based learning": ["Design-based learning", "DBL"],
        "Evidence-centred design approach": ["Evidence-centred design approach", "ECD"],
        "Gamification": ["Gamification"],
        "Reverse engineering pedagogy": ["Reverse engineering pedagogy", "REP"],
        "Technology-enhanced learning": ["Technology-enhanced learning", "TEL"],
        "Collaborative learning": ["Collaborative learning"],
        "Cooperative learning": ["Cooperative learning"],
        "Flipped classroom": ["Flipped classroom"],
        "Game-based learning": ["Game-based learning", "GBL"],
        "Inquiry-based learning": ["Inquiry-based learning", "IBL"],
        "Personalized learning": ["Personalized learning"],
        "Problem-based learning": ["Problem-based learning", "PBL"],
        "Project-based learning": ["Project-based learning", "PBL"],
        "Universal design for learning": ["Universal design for learning", "UDL"]
    },
    "Herramientas Tecnológicas": {
        "Alice": ["Alice"],
        "Arduino": ["Arduino"],
        "Scratch": ["Scratch"],
        "ScratchJr": ["ScratchJr"],
        "Blockly Games": ["Blockly Games", "Blockly"],
        "Code.org": ["Code.org"],
        "CodeCombat": ["CodeCombat", "Code Combat"],
        "CS Unplugged": ["CS Unplugged", "Computer Science Unplugged"],
        "Robot Turtles": ["Robot Turtles"],
        "Hello Ruby": ["Hello Ruby"],
        "Kodable": ["Kodable"],
        "LightbotJr": ["LightbotJr", "Lightbot Jr"],
        "KIBO robots": ["KIBO robots", "KIBO"],
        "BEE BOT": ["BEE BOT", "Bee-Bot"],
        "CUBETTO": ["CUBETTO"],
        "Minecraft": ["Minecraft", "Minecraft Education"],
        "Agent Sheets": ["Agent Sheets"],
        "Mimo": ["Mimo"],
        "Py-Learn": ["Py-Learn", "PyLearn"],
        "SpaceChem": ["SpaceChem"]
    }
}

